### ISSUE TITLE
#main definition breaks modals

### ISSUE THREAD

**Issue by whitemx** [bootcards/bootcards#17]
The addition of the following CSS:

``` css
#main {
  -webkit-transform: translate3d(0px, 0px, 0px);
  -moz-transform: translate3d(0px, 0px, 0px);
  -o-transform: translate3d(0px, 0px, 0px);
  -ms-transform: translate3d(0px, 0px, 0px);
  transform: translate3d(0px, 0px, 0px);
  -webkit-transition: 0.25s ease;
  -moz-transition: 0.25s ease;
  -o-transition: 0.25s ease;
  transition: 0.25s ease;  
}
#main.active-left {
  -webkit-transform: translate3d(200px, 0px, 0px);
  -moz-transform: translate3d(200px, 0px, 0px);
  -o-transform: translate3d(200px, 0px, 0px);
  -ms-transform: translate3d(200px, 0px, 0px);
  transform: translate3d(200px, 0px, 0px);
}
#main.active-right {
  -webkit-transform: translate3d(-200px, 0px, 0px);
  -moz-transform: translate3d(-200px, 0px, 0px);
  -o-transform: translate3d(-200px, 0px, 0px);
  -ms-transform: translate3d(-200px, 0px, 0px);
  transform: translate3d(-200px, 0px, 0px);
}
```

Causes modals that are placed within the body of a page (rather than being right at the end) to not work correctly. I can't see any issue with simple removing the above chunk which is what I've done with the Bootstrap Controls at the moment.
