### ISSUE TITLE
Independent scrolling of lists not working correctly

### ISSUE THREAD

**Issue by whitemx** [bootcards/bootcards#3]
The independent scrolling of lists requires the structure of the HTML markup to be 

``` css
body > .container > .row {
    height: 100%;
    padding-bottom: 50px;

}
```

So this means that if my page structure is body > form > container > row then scrolling isn't working. Workaround for me is to define a class name to apply to the row to set the height to 100%
