### ISSUE TITLE
.bootcards-container issue with modals

### ISSUE THREAD

**Issue by whitemx** [bootcards/bootcards#32]
If I position the markup for a modal anywhere inside the main .bootcards-container div the modal is hidden behind the modal-backdrop div.

if I change this line: 

``` css
.bootcards-container,.offcanvaslist-toggle{-webkit-transform:translate3d(0px,0,0);-moz-transform:translate3d(0px,0,0);-o-transform:translate3d(0px,0,0);-ms-transform:translate3d(0px,0,0);transform:translate3d(0px,0,0);-webkit-transition:.25s ease;-moz-transition:.25s ease;-o-transition:.25s ease;transition:.25s ease}
```

To this:

``` css
.offcanvaslist-toggle{-webkit-transform:translate3d(0px,0,0);-moz-transform:translate3d(0px,0,0);-o-transform:translate3d(0px,0,0);-ms-transform:translate3d(0px,0,0);transform:translate3d(0px,0,0);-webkit-transition:.25s ease;-moz-transition:.25s ease;-o-transition:.25s ease;transition:.25s ease}
```

Then the problem goes away. Is this something I can request? I have to use the .bootcards-container class for the menu system / portrait iPad functionality.
