### ISSUE TITLE
Body padding 80px

### ISSUE THREAD

**Issue by pavanputhra** [bootcards/bootcards#50]
Becaouse of following css code nav bar is displaced downwards.

```css
body {
  padding-top: 80px;
  background: #f5f5f5; 
}
```

Is the above code deliberate added and serves any purpose?
