### ISSUE TITLE
 .form-horizontal .form-group div div

### ISSUE THREAD

**Issue by DylanLukes** [bootcards/bootcards#53]
The following appears in the source for Form cards. This is... to say the least... problematic.

```css
.form-horizontal .form-group div div {
    padding: 0;
}
```
